#pragma once
#include "ReClassPrefix.h"
#include "ReClass.h"
#include "TypeSupport.h"

#include "..\Private\ReClassInfo.Implement.h"

#define SET_DEFAULT_CLASS_CTOR              RECLASS_SET_DEFAULT_CLASS_CTOR_IMPLEMENT
#define SET_CLASS_CTOR_DEST                 RECLASS_SET_CLASS_CTOR_DEST_IMPLEMENT
#define CLASS_IMPLEMENT                     RECLASS_CLASS_IMPLEMENT_IMPLEMENT

#define DECLARE_CLASS                       RECLASS_DECLARE_CLASS_IMPLEMENT
#define DECLARE_DERIVED_CLASS               RECLASS_DECLARE_DERIVED_CLASS_IMPLEMENT

#define DEFINE_CLASS_DYNAMIC                RECLASS_DEFINE_CLASS_DYNAMIC_IMPLEMENT
#define DEFINE_DERIVED_CLASS_DYNAMIC        RECLASS_DEFINE_DERIVED_CLASS_DYNAMIC_IMPLEMENT

#define DEFINE_CLASS_BEGIN                  RECLASS_DEFINE_CLASS_IMPLEMENT
#define DEFINE_CLASS_END                    RECLASS_DEFINE_CLASS_END_IMPLEMENT
#define DEFINE_DERIVED_CLASS_BEGIN          RECLASS_DEFINE_DERIVED_CLASS_BEGIN_IMPLEMENT
#define DEFINE_DERIVED_CLASS_END            RECLASS_DEFINE_DERIVED_CLASS_END_IMPLEMENT

#define DEFINE_CLASS                        RECLASS_DEFINE_CLASS_IMPLEMENT
#define DEFINE_CLASS_WITHOUT_NEW            RECLASS_DEFINE_CLASS_WITHOUT_NEW_IMPLEMENT
#define DEFINE_CLASS_IMP_WITH_FLAG          RECLASS_DEFINE_CLASS_IMP_WITH_FLAG_IMPLEMENT
#define DEFINE_DERIVED_CLASS                RECLASS_DEFINE_DERIVED_CLASS_IMPLEMENT
#define DEFINE_DERIVED_CLASS_WITHOUT_NEW    RECLASS_DEFINE_DERIVED_CLASS_WITHOUT_NEW_IMPLEMENT
#define DEFINE_DERIVED_CLASS_WITH_FLAG      RECLASS_DEFINE_DERIVED_CLASS_WITH_FLAG_IMPLEMENT

#define REGISTER_CLASS_BEGIN                RECLASS_REGISTER_CLASS_BEGIN_IMPLEMENT
#define REGISTER_CLASS_END                  RECLASS_REGISTER_CLASS_END_IMPLEMENT
#define REGISTER_DERIVED_CLASS_BEGIN        RECLASS_REGISTER_DERIVED_CLASS_BEGIN_IMPLEMENT
#define REGISTER_DERIVED_CLASS_END          RECLASS_REGISTER_DERIVED_CLASS_END_IMPLEMENT

#define REGISTER_CLASS                      RECLASS_REGISTER_CLASS_IMPLEMENT
#define REGISTER_CLASS_WITHOUT_NEW          RECLASS_REGISTER_CLASS_WITHOUT_NEW_IMPLEMENT
#define REGISTER_CLASS_WITH_FLAG            RECLASS_REGISTER_CLASS_WITH_FLAG_IMPLEMENT
#define REGISTER_DERIVED_CLASS              RECLASS_REGISTER_DERIVED_CLASS_IMPLEMENT
#define REGISTER_DERIVED_CLASS_WITHOUT_NEW  RECLASS_REGISTER_DERIVED_CLASS_WITHOUT_NEW_IMPLEMENT
#define REGISTER_DERIVED_CLASS_WITH_FLAG    RECLASS_REGISTER_DERIVED_CLASS_WITH_FLAG_IMPLEMENT

#define DECLARE_INTERFACE                   RECLASS_DECLARE_INTERFACE_IMPLEMENT
#define DEFINE_INTERFACE                    RECLASS_DEFINE_INTERFACE_IMPLEMENT

#define DEFINE_INTERFACE_BEGIN              RECLASS_DEFINE_INTERFACE_BEGIN_IMPLEMENT
#define DEFINE_INTERFACE_END                RECLASS_DEFINE_INTERFACE_END_IMPLEMENT

#define DECLARE_DERIVED_INTERFACE           RECLASS_DECLARE_DERIVED_INTERFACE_IMPLEMENT
#define DEFINE_DERIVED_INTERFACE            RECLASS_DEFINE_DERIVED_INTERFACE_IMPLEMENT

#define DEFINE_DERIVED_INTERFACE_BEGIN      RECLASS_DEFINE_DERIVED_INTERFACE_BEGIN_IMPLEMENT
#define DEFINE_DERIVED_INTERFACE_END        RECLASS_DEFINE_DERIVED_INTERFACE_END_IMPLEMENT